# Generated by Django 2.2.16 on 2021-05-10 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0013_auto_20190816_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='grant',
            name='claims',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='nonce',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='idtoken',
            name='jti',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False, verbose_name='JWT Token ID'),
        ),
        migrations.AlterField(
            model_name='application',
            name='algorithm',
            field=models.CharField(blank=True, choices=[('', 'No OIDC support'), ('RS256', 'RSA with SHA-2 256'), ('HS256', 'HMAC with SHA-2 256')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='grant',
            name='redirect_uri',
            field=models.TextField(),
        ),
    ]
